# -*- coding: utf-8 -*-
"""bfs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZ8p1XmArMf0ucCE_vg-FD00d7N9ChMf
"""

# Graph representation using adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# BFS algorithm using a queue
def bfs(graph, start):
    visited = set()
    queue = [start]

    while queue:
        vertex = queue.pop(0)

        if vertex not in visited:
            visited.add(vertex)
            print(vertex, end=' ')

            for neighbor in graph[vertex]:
                if neighbor not in visited:
                    queue.append(neighbor)

# Example usage
bfs(graph, 'A')
# Output: A B C D E F