# -*- coding: utf-8 -*-
"""sorting_two_sorted_arrays_in_0(n)_time.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OWgiqs_GvxkcQIjOaNr-b4VrsZsvZllP
"""

def merge_sorted_arrays(array1, array2):
    result = [0] * (len(array1) + len(array2))
    i, j, k = 0, 0, 0

    while i < len(array1) and j < len(array2):
        if array1[i] < array2[j]:
            result[k] = array1[i]
            i += 1
        else:
            result[k] = array2[j]
            j += 1
        k += 1

    while i < len(array1):
        result[k] = array1[i]
        i += 1
        k += 1

    while j < len(array2):
        result[k] = array2[j]
        j += 1
        k += 1

    return result

array1 = []
array2 = []
n1 = int(input("Enter N1 : "))
print("Elements - ")
for i in range(0, n1):
    ele = int(input())
    array1.append(ele)

n2 = int(input("Enter N2 : "))
print("Elements - ")
for i in range(0, n2):
    ele = int(input())
    array2.append(ele)
result = merge_sorted_arrays(array1,array2)
print(result)